// Job positions dropdown options
export const jobPositions = [
  { name: 'Intern', value: 'intern' },
  { name: 'Trainee', value: 'trainee' },
  { name: 'Apprentice', value: 'apprentice' },
  { name: 'Junior', value: 'junior' },
  { name: 'Assistant', value: 'assistant' },
  { name: 'Associate', value: 'associate' },
  { name: 'Coordinator', value: 'coordinator' },
  { name: 'Specialist', value: 'specialist' },
  { name: 'Analyst', value: 'analyst' },
  { name: 'Engineer', value: 'engineer' },
  { name: 'Consultant', value: 'consultant' },
  { name: 'Mid-Level', value: 'mid-level' },
  { name: 'Senior', value: 'senior' },
  { name: 'Lead', value: 'lead' },
  { name: 'Supervisor', value: 'supervisor' },
  { name: 'Principal', value: 'principal' },
  { name: 'Team Lead', value: 'team-lead' },
  { name: 'Manager', value: 'manager' },
  { name: 'Senior Manager', value: 'senior-manager' },
  { name: 'Program Manager', value: 'program-manager' },
  { name: 'Department Head', value: 'department-head' },
  { name: 'Head of [Function]', value: 'head-of-function' },
  { name: 'Director', value: 'director' },
  { name: 'Senior Director', value: 'senior-director' },
  { name: 'Vice President (VP)', value: 'vice-president' },
  { name: 'Senior Vice President (SVP)', value: 'senior-vice-president' },
  { name: 'Executive Vice President (EVP)', value: 'executive-vice-president' },
  { name: 'President', value: 'president' },
  { name: 'Managing Director (MD)', value: 'managing-director' },
  { name: 'Chief Executive Officer (CEO)', value: 'ceo' },
  { name: 'Chief Operating Officer (COO)', value: 'coo' },
  { name: 'Chief Financial Officer (CFO)', value: 'cfo' },
  { name: 'Chief Technology Officer (CTO)', value: 'cto' },
  { name: 'Chief Marketing Officer (CMO)', value: 'cmo' },
  { name: 'Chief Human Resources Officer (CHRO)', value: 'chro' },
  { name: 'Chief Information Officer (CIO)', value: 'cio' },
  { name: 'Lecturer', value: 'lecturer' },
  { name: 'Assistant Professor', value: 'assistant-professor' },
  { name: 'Associate Professor', value: 'associate-professor' },
  { name: 'Professor', value: 'professor' },
  { name: 'Dean', value: 'dean' },
  { name: 'Chancellor', value: 'chancellor' },
  { name: 'Resident', value: 'resident' },
  { name: 'Attending', value: 'attending' },
  { name: 'Consultant (Medical)', value: 'consultant-medical' },
  { name: 'Chief Physician', value: 'chief-physician' },
  { name: 'Other', value: 'other' },
];

// Ethiopian cities and locations for autocomplete
export const locations = [
  // Major Cities
  'Addis Ababa',
  'Dire Dawa',
  'Mekelle',
  'Gondar',
  'Bahir Dar',
  'Hawassa',
  'Jimma',
  'Adama',
  'Dessie',
  'Aksum',
  'Debre Birhan',
  'Shashemene',
  'Jijiga',
  'Gambela',
  'Harar',
  'Nekemte',
  'Wolaita Sodo',
  'Kombolcha',
  'Dembidolo',
  'Sodo',
  'Bonga',
  'Asella',
  'Arba Minch',
  'Debre Markos',
  'Mizan Teferi',
  'Gore',

  // Additional Cities and Towns
  'Adigrat',
  'Adwa',
  'Alaba Kulito',
  'Ambo',
  'Arsi Negele',
  'Assosa',
  'Awasa',
  'Bale Robe',
  'Bati',
  'Bedele',
  'Bishoftu',
  'Boditi',
  'Butajira',
  'Chiro',
  'Dangila',
  'Debre Tabor',
  'Debre Zeyit',
  'Dila',
  'Durame',
  'Finote Selam',
  'Gimbi',
  'Goba',
  'Gode',
  'Hagere Hiywet',
  'Hagere Maryam',
  'Hosaena',
  'Humera',
  'Inda Silase',
  'Jinka',
  'Kebri Dehar',
  'Kemise',
  'Kibre Mengist',
  'Kofele',
  'Konso',
  'Lalibela',
  'Maji',
  'Meki',
  'Mersa',
  'Metu',
  'Mojo',
  'Moyale',
  'Nazret',
  'Negele',
  'Robe',
  'Sebeta',
  'Sendafa',
  'Shakiso',
  'Shambu',
  'Shire',
  'Sire',
  'Tepi',
  'Tulu Bolo',
  'Waliso',
  'Weldiya',
  'Werabe',
  'Wolayita Sodo',
  'Woldia',
  'Wukro',
  'Yabelo',
  'Yirga Alem',
  'Ziway',

  // Special Administrative Areas
  'Addis Ababa',
  'Dire Dawa',

  // Remote/Other options
  'Remote',
  'Anywhere in Ethiopia',
];

// Industry dropdown options (from job post form)
export const industries = [
  { name: 'Information Technology', value: 'InformationTechnology' },
  { name: 'Healthcare', value: 'Healthcare' },
  { name: 'Finance', value: 'Finance' },
  { name: 'Education', value: 'Education' },
  { name: 'Manufacturing', value: 'Manufacturing' },
  { name: 'Retail', value: 'Retail' },
  { name: 'Marketing', value: 'Marketing' },
  { name: 'Sales', value: 'Sales' },
  { name: 'Consulting', value: 'Consulting' },
  { name: 'Other', value: 'Other' },
];
